### ISSUE TITLE
X_train.txt and Y_train.txt

### ISSUE THREAD

**Issue by kli017** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#11]
Hello, Thanks for sharing this great project. I was wondering could you provide a simple example of X_train.txt and Y_train.txt so I can create the input data by myself. Cause I am using the tf_openpose.
Thanks  a lot!

**Comment by kli017** [comment]
Sorry, just noticed the link of dataset. Thanks.

**Comment by ghost** [comment]
hello @kli017 
Can you tell me how to train with tf_openpose?
