### ISSUE TITLE
Can we get to know whats happening inside the Basic(tf.LSTM_cell)and multiRNNcell? Like How each matrices are multiplied and how do we get output?

### ISSUE THREAD

**Issue by saurinshah96** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#15]

**Comment by stuarteiffert** [comment]
Have a look at the documentation from tensorflow, and read up on how RNNs work in general:

https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/MultiRNNCell

http://colah.github.io/posts/2015-08-Understanding-LSTMs/

**Comment by saurinshah96** [comment]
Yes, I know general lstm architecture. Is it the same used in tensorflow?

Thanks,
Saurin

**Comment by stuarteiffert** [comment]
Yes
