### ISSUE TITLE
Model works only under the same angle and body location?

### ISSUE THREAD

**Issue by KristianDukov** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#18]
Hello All!

I was just wondering if based on the model implemented, trying to test on actions, shot from a different angle will be recognized. Also about the location of the body, but I assume with normalization this can be minimized.

Best Regards,
Kris

**Comment by stuarteiffert** [comment]
Hi Kristian,
You're right, the model is optimised for only the angles in the training dataset. It would likely perform reasonably well at angles in between, but would need testing to confirm. For any real world application we would definitely want to increase the dataset to include a wider range of angles, possibly also vertically tilting. 
I haven't normalised the data with regards to position in frame, or scale, but if that was done position would not be an issue.

Regards,
Stuart
