### ISSUE TITLE
How to restore model in seperate application to run prediction on new sample?

### ISSUE THREAD

**Issue by arvindchandel** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#30]
I saved the model using tf.train.saver and trying to restore like below:
with tf.Session() as sess:
new_saver = tf.train.import_meta_graph('model.ckpt.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./'))

Now when i am trying to run the sess on new sample,
preds = sess.run( [pred], feed_dict={ x: X_val }
i am getting error pred not defined.

**Comment by arvindchandel** [comment]
Fixed it.

**Comment by zlg9folira** [comment]
I ran into the same issue, could you provide more details or put missing lines in the code ? I am trying to load the pre-saved model in a different python script and do prediction there. @arvindchandel
